spring:
  profiles:
    active: dev #指定为开发环境
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  #数据库配置
  datasource:
    url: jdbc:mysql://192.168.2.218:3306/b2c_en?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: enation752513
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: false
  #rabbitmq
  rabbitmq:
    host: 192.168.2.219
    port: 5672
    username: b2c
    password: b2c
    virtual-host: b2c

  #elasticsearch配置
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.2.219:9300
      index-name: b2c

#redis 配置
redis:
  type: standalone
  config :
    type: manual
  host: localhost
  port: 6379
  password:
  maxIdle: 500
  maxTotal: 500
  maxWaitMillis: -1


# 开发环境日志为debug
logging:
  level:
    org.springframework: ERROR
    com.enation.app : DEBUG

#java 系统配置
shopflix:
  product: stand #定义系统标准产品，微服务指定为： microservice
  license[0]: abcde #license请向售后人员索要
  #token加密秘钥，请务必更换此词串，且注意保密
  token-secret: 85d6ce9da4e943ff4dcd367ab3d94164
  timeout:
    accessTokenTimeout:  1200 #访问token失效时间 单位秒
    refreshTokenTimeout: 1800 #刷新token失效时间 单位秒
    captchaTimout:  120       #验证码失效时间 单位秒
    smscodeTimout: 120        #短信验证码失效时间 单位秒
  isDemoSite: no
  ssl: off #是否开启ssl
  domain:
    buyer: buyer.javamall.com.cn #配置为您买家端PC的域名
    mobileBuyer: m.buyer.javamall.com.cn  #配置为您买家端WAP的域名
    callback: api.buyerjavamall.com.cn #请配置为您站点的买家端的api域名，如果不配置此项默认读取站点买家端api的域名，用来做支付新人登录回调
